{"cells":[{"cell_type":"markdown","metadata":{"id":"gQq_-NDM_G89"},"source":["# Errors and Exceptions"]},{"cell_type":"markdown","metadata":{"id":"oUXsB3Zk_G9C"},"source":["![error.gif](attachment:error.gif)"]},{"cell_type":"markdown","metadata":{"id":"DIL9Aii6_G9C"},"source":["If you can hear that image then you are in the right place :)\n","\n","It is always helpful when someone else is indicating what is wrong on our actions in code that's why error messages are important to be read carefully and be taken into consideration seriously.\n","\n","Python has [built-in](https://www.programiz.com/python-programming/exceptions) exceptions to raise and indicate errors in the code. But what is the actual difference between syntax errors and exceptions?\n","\n","**Syntax error** is a mistake in the use of the Python language, and is analogous to spelling or grammar mistakes in a language like English. Such errors are preventing the program to be executed thus it stops.\n","\n","\n","Example:"]},{"cell_type":"code","execution_count":3,"metadata":{"id":"fzmChhpD_G9D","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710239118419,"user_tz":-60,"elapsed":221,"user":{"displayName":"Lionel Dorange (The Orange)","userId":"08146851426162097203"}},"outputId":"f8a5646f-09c8-4f96-af26-b8eba53af95e"},"outputs":[{"output_type":"stream","name":"stdout","text":["You are allowed to drink\n"]}],"source":["# initialize the amount variable\n","age = 30\n","\n","# check if the user is eligible to drink\n","if(age > 18):\n","  print(\"You are allowed to drink\")"]},{"cell_type":"markdown","metadata":{"id":"56Joil6l_G9F"},"source":["Error messages provide information about the line that caused the error by tracing back to the function calls that lead to this instruction. The line numbers of the function calls are displayed in the error message to enable quick correction of the code. The parser repeats the offending line and displays a little ‘arrow’ pointing at the earliest point in the line where the error was detected."]},{"cell_type":"markdown","metadata":{"id":"L83YwVXj_G9H"},"source":["**Exception** is when there is nothing wrong in syntax but something is wrong and it changes the flow of the program. Exceptions have a lot of types but below we will see only **3 types** : *ZeroDivisionError, TypeError* and *NameError* each one with its own meaning. Let's see some examples in order to get the differences better.\n","\n","Example 1 :"]},{"cell_type":"code","execution_count":14,"metadata":{"id":"__-tLO13_G9H","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710240574762,"user_tz":-60,"elapsed":4192,"user":{"displayName":"Lionel Dorange (The Orange)","userId":"08146851426162097203"}},"outputId":"78ee748b-ca44-493f-fbc0-5c91598ea92d"},"outputs":[{"output_type":"stream","name":"stdout","text":["Enter integer: 1\n","1 1.0\n"]}],"source":["a = input(\"Enter integer: \")\n","num = int(a)\n","inverse = 1 / num\n","print(num, inverse)\n","\n","## ATTENTION! What happens if the user enters a null or non-numeric value? The program will stop and raise an error as shown below."]},{"cell_type":"markdown","metadata":{"id":"6Ta7BbzU_G9I"},"source":["Example 2:"]},{"cell_type":"code","execution_count":13,"metadata":{"id":"rtuSS_En_G9I","executionInfo":{"status":"ok","timestamp":1710240443126,"user_tz":-60,"elapsed":239,"user":{"displayName":"Lionel Dorange (The Orange)","userId":"08146851426162097203"}}},"outputs":[],"source":["y = 0\n","x = 5 + y"]},{"cell_type":"markdown","metadata":{"id":"ME83npcH_G9J"},"source":["Example 3:"]},{"cell_type":"code","execution_count":12,"metadata":{"id":"lGI4cVrl_G9J","executionInfo":{"status":"ok","timestamp":1710240422361,"user_tz":-60,"elapsed":227,"user":{"displayName":"Lionel Dorange (The Orange)","userId":"08146851426162097203"}}},"outputs":[],"source":["a = '2' + '5'"]},{"cell_type":"markdown","metadata":{"id":"NOMgXAFN_G9K"},"source":["Can you spot the differences?\n","\n","Interesting right? You can now understand , more or less, what is the problem with your code. Hourayyyy!\n","\n","Let's now try to see how we can handle such exceptions and make our life easier.\n"]},{"cell_type":"markdown","metadata":{"id":"EX1H5Adm_G9K"},"source":["# Exception handling"]},{"cell_type":"markdown","metadata":{"id":"FP9uimBi_G9L"},"source":["## Try and except\n","\n","**Try** and **except** statements are used in order to catch and eventually handle exceptions in Python. The commands that may cause issues are written inside the try clause and the commands that will handle the exceptionare written inside except clause.\n","\n","\n","As we saw above, if you try to divide with 0, you will get the ZeroDivisionError, so how can we handle that?"]},{"cell_type":"code","execution_count":15,"metadata":{"id":"09anax1x_G9L","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710240620346,"user_tz":-60,"elapsed":247,"user":{"displayName":"Lionel Dorange (The Orange)","userId":"08146851426162097203"}},"outputId":"e53f95e1-dcf1-49db-f571-7ae7200f9ecb"},"outputs":[{"output_type":"stream","name":"stdout","text":["Trying to divide with zero\n","Finished\n"]}],"source":["try:\n","    3 / 0\n","except:\n","    print(\"Trying to divide with zero\")\n","\n","print(\"Finished\")"]},{"cell_type":"markdown","metadata":{"id":"mNKcUAg0_G9M"},"source":["It worked!!! We didn't get any errors, but instead we got a message which dedicates what is wrong and we can continue our execution as we want.\n","\n","So, how this is actually working:\n","- First, whatever is in the try clause is being executed.\n","- If what is written there, has no issues, then the except clause is been ignored and the entire try statement is completed.\n","- If something is wrong, then the except clause is being executed\n"]},{"cell_type":"markdown","metadata":{"id":"mwZtqJrh_G9M"},"source":["One try clause can have multiple except clauses to specify handlers for different exceptions.\n","\n","Now, we will try to avoid the exceptions mentioned above by rewriting our code as follows.   \n","We have the ability to capture the type of exception."]},{"cell_type":"code","execution_count":16,"metadata":{"id":"hWOYpgah_G9M","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710240647801,"user_tz":-60,"elapsed":210,"user":{"displayName":"Lionel Dorange (The Orange)","userId":"08146851426162097203"}},"outputId":"29f8064f-17cd-445f-c3ef-0a7349be9f37"},"outputs":[{"output_type":"stream","name":"stdout","text":["Error: You can't divide by zero\n"]}],"source":["try:\n","    3 / 0\n","except ZeroDivisionError:\n","    print(\"Error: You can't divide by zero\")\n","except ValueError:\n","    print(\"Error: Non-numeric value\")\n","except BaseException:\n","    print(\"Error: there is a problem\")"]},{"cell_type":"code","execution_count":17,"metadata":{"id":"hvQ_fowF_G9N","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710240659202,"user_tz":-60,"elapsed":260,"user":{"displayName":"Lionel Dorange (The Orange)","userId":"08146851426162097203"}},"outputId":"b2ac98ec-44c2-4ca0-9429-569ecd4396ae"},"outputs":[{"output_type":"stream","name":"stdout","text":["Error: Non-numeric value\n"]}],"source":["try:\n","    3 / int(\"ssss\")\n","except ZeroDivisionError:\n","    print(\"Error: You can't divide by zero\")\n","except ValueError:\n","    print(\"Error: Non-numeric value\")\n","except BaseException:\n","    print(\"Error: there is a problem\")"]},{"cell_type":"markdown","metadata":{"id":"pyvcdOjS_G9O"},"source":["You can also except multiple exception as one. If you need to know which one was raised, you can save the exception's error message if you want to print it."]},{"cell_type":"code","execution_count":18,"metadata":{"id":"Mn4WvIDE_G9O","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710240666348,"user_tz":-60,"elapsed":213,"user":{"displayName":"Lionel Dorange (The Orange)","userId":"08146851426162097203"}},"outputId":"a7f0ca32-8be5-40f3-9c0a-cc6e766339f2"},"outputs":[{"output_type":"stream","name":"stdout","text":["Error:  invalid literal for int() with base 10: 'ssss'\n"]}],"source":["try:\n","    3 / int(\"ssss\")\n","except (ZeroDivisionError, ValueError, BaseException) as ex:\n","    print(\"Error: \", ex)"]},{"cell_type":"markdown","metadata":{"id":"9ipxuUJ3_G9O"},"source":["### Finally and else\n","\n","As alternatives at the end of our exception handling we can use two other reserved keywords :  `finally` and `else`.  \n","`else` is executed when no other exception is being detected and `finally` is a block that is executed after all other blocks have been executed, regardless of whether there was an exception or not, and **even if the program crashes**."]},{"cell_type":"code","execution_count":19,"metadata":{"id":"rQNExfLh_G9P","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710240674021,"user_tz":-60,"elapsed":315,"user":{"displayName":"Lionel Dorange (The Orange)","userId":"08146851426162097203"}},"outputId":"bda4eaa5-0f6b-43be-ba35-942cdda302b6"},"outputs":[{"output_type":"stream","name":"stdout","text":["Everything is ok\n"]}],"source":["try:\n","    3 / 3\n","except ZeroDivisionError:\n","    print(\"Error: You can't divide by zero\")\n","except ValueError:\n","    print(\"Error: Non-numeric value\")\n","except BaseException:\n","    print(\"Error: there is a problem\")\n","else:\n","    print(\"Everything is ok\")"]},{"cell_type":"code","execution_count":20,"metadata":{"id":"zSDlDIPN_G9P","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710240724186,"user_tz":-60,"elapsed":276,"user":{"displayName":"Lionel Dorange (The Orange)","userId":"08146851426162097203"}},"outputId":"7718d796-33e0-4b88-8891-1bac66770929"},"outputs":[{"output_type":"stream","name":"stdout","text":["Error: You can't divide by zero\n","I'll do executing in the end no matter what..\n"]}],"source":["try:\n","    3 / 0\n","except ZeroDivisionError:\n","    print(\"Error: You can't divide by zero\")\n","except ValueError:\n","    print(\"Error: Non-numeric value\")\n","except BaseException:\n","    print(\"Error: there is a problem\")\n","finally:\n","    print(\"I'll do executing in the end no matter what..\")"]},{"cell_type":"markdown","metadata":{"id":"0Vxco-NE_G9Q"},"source":["### Raise"]},{"cell_type":"markdown","metadata":{"id":"dIfFZN1c_G9Q"},"source":["Sometimes it is fun to make mistakes, same when you are coding. Therefore, we have the statement `raise` which makes it possible to trigger exceptions by ourselves."]},{"cell_type":"markdown","metadata":{"id":"DKjwRcS7_G9R"},"source":["`raise` is a Python statement that can trigger any `Exception`. This means that an error is explicitly triggered."]},{"cell_type":"code","execution_count":21,"metadata":{"id":"AWK4gXlM_G9R","colab":{"base_uri":"https://localhost:8080/","height":297},"executionInfo":{"status":"error","timestamp":1710240790003,"user_tz":-60,"elapsed":278,"user":{"displayName":"Lionel Dorange (The Orange)","userId":"08146851426162097203"}},"outputId":"9d7a4bfe-5beb-4d1e-9384-bb85ef140e33"},"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-21-5b1616062354>\u001b[0m in \u001b[0;36m<cell line: 8>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      7\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 8\u001b[0;31m \u001b[0mdivision\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m5\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-21-5b1616062354>\u001b[0m in \u001b[0;36mdivision\u001b[0;34m(num, div)\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mdivision\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnum\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdiv\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mdiv\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0mZeroDivisionError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mnum\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0mdiv\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mZeroDivisionError\u001b[0m: "]}],"source":["def division(num, div):\n","    if div == 0:\n","        raise ZeroDivisionError()\n","    else:\n","        return num / div\n","\n","\n","division(5, 0)"]},{"cell_type":"markdown","metadata":{"id":"r3YzEbUD_G9R"},"source":["We can agree that the `division()` function is completely useless! This was just to showcase the purpose of `raise`.\n","\n","### Creating an exception\n","As you can imagine, we can create our own exceptions.\n","Just create a class that will inherit from the `Exception` class.\n","\n","*Note that it is good practice to add docstring to document the exception's purpose.*"]},{"cell_type":"code","execution_count":22,"metadata":{"id":"n_9sihvG_G9S","executionInfo":{"status":"ok","timestamp":1710240818498,"user_tz":-60,"elapsed":323,"user":{"displayName":"Lionel Dorange (The Orange)","userId":"08146851426162097203"}}},"outputs":[],"source":["class MyError(Exception):\n","    \"\"\"Raised when demonstating exception handling.\"\"\"\n","\n","    pass"]},{"cell_type":"code","execution_count":23,"metadata":{"id":"Lc96VZN7_G9S","colab":{"base_uri":"https://localhost:8080/","height":141},"executionInfo":{"status":"error","timestamp":1710240823243,"user_tz":-60,"elapsed":532,"user":{"displayName":"Lionel Dorange (The Orange)","userId":"08146851426162097203"}},"outputId":"16dd377a-48b3-421b-850e-20fe8213736d"},"outputs":[{"output_type":"error","ename":"MyError","evalue":"Hello","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mMyError\u001b[0m                                   Traceback (most recent call last)","\u001b[0;32m<ipython-input-23-e6e7a22c0cb6>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mraise\u001b[0m \u001b[0mMyError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Hello\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mMyError\u001b[0m: Hello"]}],"source":["raise MyError(\"Hello\")"]},{"cell_type":"markdown","metadata":{"id":"FnTFrIJl_G9S"},"source":["### Wrap it together\n","\n","It is common to add a try/except statement around function.\n","\n","A simple example here:"]},{"cell_type":"code","execution_count":24,"metadata":{"id":"DYsde5N1_G9T","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710240844714,"user_tz":-60,"elapsed":322,"user":{"displayName":"Lionel Dorange (The Orange)","userId":"08146851426162097203"}},"outputId":"c3508087-f799-4ca4-8d6d-771ba71a0ce1"},"outputs":[{"output_type":"stream","name":"stdout","text":["Can't compute result:  You can't input 0 as a second argument!\n"]}],"source":["def division(num, div):\n","    if div == 0:\n","        raise ZeroDivisionError(\"You can't input 0 as a second argument!\")\n","    else:\n","        return num / div\n","\n","try:\n","    division(5, 0)\n","except ZeroDivisionError as ex:\n","    print(\"Can't compute result: \", ex)"]},{"cell_type":"markdown","metadata":{"id":"DmzjSeVe_G9T"},"source":["### Final warning\n","\n","Try/except are great! But as all good things, you should not abuse it.\n","\n","The catch is to try/except everything without scepcific exception.\n","You risk to end up not seeing errors you does not expect without understanding what is wrong.\n","\n","To avoid that, we recommend always to add a print statement when you except something."]},{"cell_type":"markdown","metadata":{"id":"bvY-uour_G9T"},"source":["## Explore further:\n","- https://www.w3schools.com/python/python_try_except.asp\n","- https://www.tutorialspoint.com/python/python_exceptions.htm\n","- https://realpython.com/python-exceptions/"]},{"cell_type":"markdown","metadata":{"id":"2bKbOaYk_G9U"},"source":["## Your turn\n","\n","Based on what you discovered today and on some external research, write a Python code for each of those problems **by using exceptions**:\n","\n","1. Ask the user to input two numbers and perform division. Use a try-except block to handle the ZeroDivisionError exception.\n","2. Create a list of integers. Ask the user to input an index to access an element from the list. Use a try-except block to handle the IndexError exception.\n","3. Ask the user to input a number. Convert the user input to an integer or float using int() or float(). Use a try-except block to handle the ValueError exception.\n","4. Create a custom exception called \"InvalidAgeException\". Write a function that takes an age as input and raises this exception if the age is negative or greater than 150.\n","5. Create a function that takes two numbers as input and performs division. If the divisor is zero, raise a custom exception called \"InvalidDivisorException\". Use a try-except block to handle this exception."]},{"cell_type":"markdown","metadata":{"id":"1N9JV4ld_G9U"},"source":[]}],"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.5"},"vscode":{"interpreter":{"hash":"65c45682600b822032a055cbf04f0dc5abe5e3c026f7225f43ce560cd84c5728"}},"colab":{"provenance":[]}},"nbformat":4,"nbformat_minor":0}