{"cells":[{"cell_type":"markdown","metadata":{"id":"gQq_-NDM_G89"},"source":["# Errors and Exceptions"]},{"cell_type":"markdown","metadata":{"id":"oUXsB3Zk_G9C"},"source":["![error.gif](attachment:error.gif)"]},{"cell_type":"markdown","metadata":{"id":"DIL9Aii6_G9C"},"source":["If you can hear that image then you are in the right place :)\n","\n","It is always helpful when someone else is indicating what is wrong on our actions in code that's why error messages are important to be read carefully and be taken into consideration seriously.\n","\n","Python has [built-in](https://www.programiz.com/python-programming/exceptions) exceptions to raise and indicate errors in the code. But what is the actual difference between syntax errors and exceptions?\n","\n","**Syntax error** is a mistake in the use of the Python language, and is analogous to spelling or grammar mistakes in a language like English. Such errors are preventing the program to be executed thus it stops.\n","\n","\n","Example:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"fzmChhpD_G9D"},"outputs":[],"source":["# initialize the amount variable\n","age = 30\n","\n","# check if the user is eligible to drink\n","if(age > 18)\n","print(\"You are allowed to drink\")"]},{"cell_type":"markdown","metadata":{"id":"56Joil6l_G9F"},"source":["Error messages provide information about the line that caused the error by tracing back to the function calls that lead to this instruction. The line numbers of the function calls are displayed in the error message to enable quick correction of the code. The parser repeats the offending line and displays a little ‘arrow’ pointing at the earliest point in the line where the error was detected."]},{"cell_type":"markdown","metadata":{"id":"L83YwVXj_G9H"},"source":["**Exception** is when there is nothing wrong in syntax but something is wrong and it changes the flow of the program. Exceptions have a lot of types but below we will see only **3 types** : *ZeroDivisionError, TypeError* and *NameError* each one with its own meaning. Let's see some examples in order to get the differences better.\n","\n","Example 1 :"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"__-tLO13_G9H","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710145903399,"user_tz":-60,"elapsed":3452,"user":{"displayName":"Amandine Van de Winckel","userId":"01836789638994642216"}},"outputId":"0c032d7a-8653-4cde-8f0e-dbae0e1ebd08"},"outputs":[{"output_type":"stream","name":"stdout","text":["Enter integer: 25\n","25 0.04\n"]}],"source":["a = input(\"Enter integer: \")\n","num = int(a)\n","inverse = 1 / num\n","print(number, inverse)\n","\n","## ATTENTION! What happens if the user enters a null or non-numeric value? The program will stop and raise an error as shown below.\n","\n","\"\"\"correction\n","a = input(\"Enter integer: \")\n","num = int(a)\n","inverse = 1 / num\n","print(number, inverse)\n","\"\"\""]},{"cell_type":"markdown","metadata":{"id":"6Ta7BbzU_G9I"},"source":["Example 2:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"rtuSS_En_G9I","colab":{"base_uri":"https://localhost:8080/","height":141},"executionInfo":{"status":"error","timestamp":1710145956749,"user_tz":-60,"elapsed":303,"user":{"displayName":"Amandine Van de Winckel","userId":"01836789638994642216"}},"outputId":"dcf47693-2ead-46a1-9478-fe7d1868910d"},"outputs":[{"output_type":"error","ename":"NameError","evalue":"name 'y' is not defined","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mNameError\u001b[0m                                 Traceback (most recent call last)","\u001b[0;32m<ipython-input-4-0662eb7d97fd>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0mx\u001b[0m \u001b[0;34m=\u001b[0m \u001b[0;36m5\u001b[0m \u001b[0;34m+\u001b[0m \u001b[0my\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mNameError\u001b[0m: name 'y' is not defined"]}],"source":["x = 5 + y\n","\n","\"\"\"correction\n","y = 10  #  ou toute autre valeur\n","x = 5 + y\n","print(x)\n","\"\"\"\n"]},{"cell_type":"markdown","metadata":{"id":"ME83npcH_G9J"},"source":["Example 3:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"lGI4cVrl_G9J","colab":{"base_uri":"https://localhost:8080/","height":106},"executionInfo":{"status":"error","timestamp":1710146115611,"user_tz":-60,"elapsed":243,"user":{"displayName":"Amandine Van de Winckel","userId":"01836789638994642216"}},"outputId":"423de223-9ffa-451d-dcb4-68f92c0723c3"},"outputs":[{"output_type":"error","ename":"SyntaxError","evalue":"incomplete input (<ipython-input-5-0366a45b8bf9>, line 3)","traceback":["\u001b[0;36m  File \u001b[0;32m\"<ipython-input-5-0366a45b8bf9>\"\u001b[0;36m, line \u001b[0;32m3\u001b[0m\n\u001b[0;31m    \"\"\"correction\u001b[0m\n\u001b[0m    ^\u001b[0m\n\u001b[0;31mSyntaxError\u001b[0m\u001b[0;31m:\u001b[0m incomplete input\n"]}],"source":["a = '2' + 5\n","\n","\"\"\"correction\n","a = int('2') + 5\n","print(a)\n","\"\"\"\n"]},{"cell_type":"markdown","metadata":{"id":"NOMgXAFN_G9K"},"source":["Can you spot the differences?\n","\n","Interesting right? You can now understand , more or less, what is the problem with your code. Hourayyyy!\n","\n","Let's now try to see how we can handle such exceptions and make our life easier.\n"]},{"cell_type":"markdown","metadata":{"id":"EX1H5Adm_G9K"},"source":["# Exception handling"]},{"cell_type":"markdown","metadata":{"id":"FP9uimBi_G9L"},"source":["## Try and except\n","\n","**Try** and **except** statements are used in order to catch and eventually handle exceptions in Python. The commands that may cause issues are written inside the try clause and the commands that will handle the exceptionare written inside except clause.\n","\n","\n","As we saw above, if you try to divide with 0, you will get the ZeroDivisionError, so how can we handle that?"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"09anax1x_G9L","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710146273068,"user_tz":-60,"elapsed":308,"user":{"displayName":"Amandine Van de Winckel","userId":"01836789638994642216"}},"outputId":"0b986bbf-2b3f-4631-f26c-596d3cef6440"},"outputs":[{"output_type":"stream","name":"stdout","text":["Trying to divide with zero\n","Finished\n"]}],"source":["try:\n","    3 / 0\n","except:\n","    print(\"Trying to divide with zero\")\n","\n","print(\"Finished\")"]},{"cell_type":"markdown","metadata":{"id":"mNKcUAg0_G9M"},"source":["It worked!!! We didn't get any errors, but instead we got a message which dedicates what is wrong and we can continue our execution as we want.\n","\n","So, how this is actually working:\n","- First, whatever is in the try clause is being executed.\n","- If what is written there, has no issues, then the except clause is been ignored and the entire try statement is completed.\n","- If something is wrong, then the except clause is being executed\n"]},{"cell_type":"markdown","metadata":{"id":"mwZtqJrh_G9M"},"source":["One try clause can have multiple except clauses to specify handlers for different exceptions.\n","\n","Now, we will try to avoid the exceptions mentioned above by rewriting our code as follows.   \n","We have the ability to capture the type of exception."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"hWOYpgah_G9M","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710146313739,"user_tz":-60,"elapsed":224,"user":{"displayName":"Amandine Van de Winckel","userId":"01836789638994642216"}},"outputId":"3975a43c-53a1-4bc8-a6e4-6ef42182f786"},"outputs":[{"output_type":"stream","name":"stdout","text":["Error: You can't divide by zero\n"]}],"source":["try:\n","    3 / 0\n","except ZeroDivisionError:\n","    print(\"Error: You can't divide by zero\")\n","except ValueError:\n","    print(\"Error: Non-numeric value\")\n","except BaseException:\n","    print(\"Error: there is a problem\")"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"hvQ_fowF_G9N","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710146368412,"user_tz":-60,"elapsed":320,"user":{"displayName":"Amandine Van de Winckel","userId":"01836789638994642216"}},"outputId":"83cce725-86a7-4942-fb38-82653ff116fa"},"outputs":[{"output_type":"stream","name":"stdout","text":["Error: Non-numeric value\n"]}],"source":["try:\n","    3 / int(\"ssss\")\n","except ZeroDivisionError:\n","    print(\"Error: You can't divide by zero\")\n","except ValueError:\n","    print(\"Error: Non-numeric value\")\n","except BaseException:\n","    print(\"Error: there is a problem\")"]},{"cell_type":"markdown","metadata":{"id":"pyvcdOjS_G9O"},"source":["You can also except multiple exception as one. If you need to know which one was raised, you can save the exception's error message if you want to print it."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Mn4WvIDE_G9O","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710146421761,"user_tz":-60,"elapsed":250,"user":{"displayName":"Amandine Van de Winckel","userId":"01836789638994642216"}},"outputId":"14d19c6f-eba6-4135-a8ae-60ea2ad88e8c"},"outputs":[{"output_type":"stream","name":"stdout","text":["Error:  invalid literal for int() with base 10: 'ssss'\n"]}],"source":["try:\n","    3 / int(\"ssss\")\n","except (ZeroDivisionError, ValueError, BaseException) as ex:\n","    print(\"Error: \", ex)"]},{"cell_type":"markdown","metadata":{"id":"9ipxuUJ3_G9O"},"source":["### Finally and else\n","\n","As alternatives at the end of our exception handling we can use two other reserved keywords :  `finally` and `else`.  \n","`else` is executed when no other exception is being detected and `finally` is a block that is executed after all other blocks have been executed, regardless of whether there was an exception or not, and **even if the program crashes**."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"rQNExfLh_G9P","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710146472660,"user_tz":-60,"elapsed":301,"user":{"displayName":"Amandine Van de Winckel","userId":"01836789638994642216"}},"outputId":"45df8ae6-4fb0-412e-d9b2-39eed28a40c8"},"outputs":[{"output_type":"stream","name":"stdout","text":["Everything is ok\n"]}],"source":["try:\n","    3 / 3\n","except ZeroDivisionError:\n","    print(\"Error: You can't divide by zero\")\n","except ValueError:\n","    print(\"Error: Non-numeric value\")\n","except BaseException:\n","    print(\"Error: there is a problem\")\n","else:\n","    print(\"Everything is ok\")"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"zSDlDIPN_G9P","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710146477269,"user_tz":-60,"elapsed":314,"user":{"displayName":"Amandine Van de Winckel","userId":"01836789638994642216"}},"outputId":"90d86e5a-52bb-4bca-d5d0-3cd388ec815f"},"outputs":[{"output_type":"stream","name":"stdout","text":["Error: You can't divide by zero\n","I'll do executing in the end no matter what..\n"]}],"source":["try:\n","    3 / 0\n","except ZeroDivisionError:\n","    print(\"Error: You can't divide by zero\")\n","except ValueError:\n","    print(\"Error: Non-numeric value\")\n","except BaseException:\n","    print(\"Error: there is a problem\")\n","finally:\n","    print(\"I'll do executing in the end no matter what..\")"]},{"cell_type":"markdown","metadata":{"id":"0Vxco-NE_G9Q"},"source":["### Raise"]},{"cell_type":"markdown","metadata":{"id":"dIfFZN1c_G9Q"},"source":["Sometimes it is fun to make mistakes, same when you are coding. Therefore, we have the statement `raise` which makes it possible to trigger exceptions by ourselves."]},{"cell_type":"markdown","metadata":{"id":"DKjwRcS7_G9R"},"source":["`raise` is a Python statement that can trigger any `Exception`. This means that an error is explicitly triggered."]},{"cell_type":"code","execution_count":null,"metadata":{"id":"AWK4gXlM_G9R","colab":{"base_uri":"https://localhost:8080/","height":298},"executionInfo":{"status":"error","timestamp":1710146535248,"user_tz":-60,"elapsed":270,"user":{"displayName":"Amandine Van de Winckel","userId":"01836789638994642216"}},"outputId":"8bfb983c-ebc6-47e4-cc72-87cfa4ba5772"},"outputs":[{"output_type":"error","ename":"ZeroDivisionError","evalue":"","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mZeroDivisionError\u001b[0m                         Traceback (most recent call last)","\u001b[0;32m<ipython-input-14-5b1616062354>\u001b[0m in \u001b[0;36m<cell line: 8>\u001b[0;34m()\u001b[0m\n\u001b[1;32m      6\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      7\u001b[0m \u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 8\u001b[0;31m \u001b[0mdivision\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;36m5\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;32m<ipython-input-14-5b1616062354>\u001b[0m in \u001b[0;36mdivision\u001b[0;34m(num, div)\u001b[0m\n\u001b[1;32m      1\u001b[0m \u001b[0;32mdef\u001b[0m \u001b[0mdivision\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0mnum\u001b[0m\u001b[0;34m,\u001b[0m \u001b[0mdiv\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      2\u001b[0m     \u001b[0;32mif\u001b[0m \u001b[0mdiv\u001b[0m \u001b[0;34m==\u001b[0m \u001b[0;36m0\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0;32m----> 3\u001b[0;31m         \u001b[0;32mraise\u001b[0m \u001b[0mZeroDivisionError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m\u001b[1;32m      4\u001b[0m     \u001b[0;32melse\u001b[0m\u001b[0;34m:\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[1;32m      5\u001b[0m         \u001b[0;32mreturn\u001b[0m \u001b[0mnum\u001b[0m \u001b[0;34m/\u001b[0m \u001b[0mdiv\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n","\u001b[0;31mZeroDivisionError\u001b[0m: "]}],"source":["def division(num, div):\n","    if div == 0:\n","        raise ZeroDivisionError()\n","    else:\n","        return num / div\n","\n","\n","division(5, 0)"]},{"cell_type":"markdown","metadata":{"id":"r3YzEbUD_G9R"},"source":["We can agree that the `division()` function is completely useless! This was just to showcase the purpose of `raise`.\n","\n","### Creating an exception\n","As you can imagine, we can create our own exceptions.\n","Just create a class that will inherit from the `Exception` class.\n","\n","*Note that it is good practice to add docstring to document the exception's purpose.*"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"n_9sihvG_G9S"},"outputs":[],"source":["\"class MyError(Exception):\n","    \"\"\"Raised when demonstating exception handling.\"\"\"\n","\n","    pass"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"Lc96VZN7_G9S","colab":{"base_uri":"https://localhost:8080/","height":141},"executionInfo":{"status":"error","timestamp":1710146796866,"user_tz":-60,"elapsed":425,"user":{"displayName":"Amandine Van de Winckel","userId":"01836789638994642216"}},"outputId":"1ff2253b-944f-433e-f614-3be544aa93f1"},"outputs":[{"output_type":"error","ename":"MyError","evalue":"Hello","traceback":["\u001b[0;31m---------------------------------------------------------------------------\u001b[0m","\u001b[0;31mMyError\u001b[0m                                   Traceback (most recent call last)","\u001b[0;32m<ipython-input-17-e6e7a22c0cb6>\u001b[0m in \u001b[0;36m<cell line: 1>\u001b[0;34m()\u001b[0m\n\u001b[0;32m----> 1\u001b[0;31m \u001b[0;32mraise\u001b[0m \u001b[0mMyError\u001b[0m\u001b[0;34m(\u001b[0m\u001b[0;34m\"Hello\"\u001b[0m\u001b[0;34m)\u001b[0m\u001b[0;34m\u001b[0m\u001b[0;34m\u001b[0m\u001b[0m\n\u001b[0m","\u001b[0;31mMyError\u001b[0m: Hello"]}],"source":["raise MyError(\"Hello\")"]},{"cell_type":"markdown","metadata":{"id":"FnTFrIJl_G9S"},"source":["### Wrap it together\n","\n","It is common to add a try/except statement around function.\n","\n","A simple example here:"]},{"cell_type":"code","execution_count":null,"metadata":{"id":"DYsde5N1_G9T","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710146829840,"user_tz":-60,"elapsed":559,"user":{"displayName":"Amandine Van de Winckel","userId":"01836789638994642216"}},"outputId":"a1d18116-ffb7-4a9b-ebaa-5c350b1e3716"},"outputs":[{"output_type":"stream","name":"stdout","text":["Can't compute result:  You can't input 0 as a second argument!\n"]}],"source":["def division(num, div):\n","    if div == 0:\n","        raise ZeroDivisionError(\"You can't input 0 as a second argument!\")\n","    else:\n","        return num / div\n","\n","try:\n","    division(5, 0)\n","except ZeroDivisionError as ex:\n","    print(\"Can't compute result: \", ex)"]},{"cell_type":"markdown","metadata":{"id":"DmzjSeVe_G9T"},"source":["### Final warning\n","\n","Try/except are great! But as all good things, you should not abuse it.\n","\n","The catch is to try/except everything without scepcific exception.\n","You risk to end up not seeing errors you does not expect without understanding what is wrong.\n","\n","To avoid that, we recommend always to add a print statement when you except something."]},{"cell_type":"markdown","metadata":{"id":"bvY-uour_G9T"},"source":["## Explore further:\n","- https://www.w3schools.com/python/python_try_except.asp\n","- https://www.tutorialspoint.com/python/python_exceptions.htm\n","- https://realpython.com/python-exceptions/"]},{"cell_type":"markdown","metadata":{"id":"2bKbOaYk_G9U"},"source":["## Your turn\n","\n","Based on what you discovered today and on some external research, write a Python code for each of those problems **by using exceptions**:\n","\n","1. Ask the user to input two numbers and perform division. Use a try-except block to handle the ZeroDivisionError exception.\n","2. Create a list of integers. Ask the user to input an index to access an element from the list. Use a try-except block to handle the IndexError exception.\n","3. Ask the user to input a number. Convert the user input to an integer or float using int() or float(). Use a try-except block to handle the ValueError exception.\n","4. Create a custom exception called \"InvalidAgeException\". Write a function that takes an age as input and raises this exception if the age is negative or greater than 150.\n","5. Create a function that takes two numbers as input and performs division. If the divisor is zero, raise a custom exception called \"InvalidDivisorException\". Use a try-except block to handle this exception."]},{"cell_type":"code","source":["#1\n","def perform_division():\n","    try:\n","        # Demander à l'utilisateur d'entrer deux nombres\n","        numerator = float(input(\"Entrez le numérateur : \"))\n","        denominator = float(input(\"Entrez le dénominateur : \"))\n","\n","        # Effectuer la division\n","        result = numerator / denominator\n","\n","        # Afficher le résultat\n","        print(\"Résultat de la division :\", result)\n","\n","    except ZeroDivisionError:\n","        # Gérer l'exception si le dénominateur est égal à zéro\n","        print(\"Erreur : Division par zéro !\")\n","    except ValueError:\n","        # Gérer l'exception si l'entrée de l'utilisateur n'est pas un nombre\n","        print(\"Erreur : Veuillez entrer des nombres valides.\")\n","\n","# Appeler la fonction pour effectuer la division\n","perform_division()\n","\n","\n","#2\n","\n","def access_list_element(my_list):\n","    try:\n","        # Demander à l'utilisateur d'entrer l'index\n","        index = int(input(\"Entrez l'index de l'élément à accéder : \"))\n","\n","        # Accéder à l'élément de la liste à l'index spécifié\n","        element = my_list[index]\n","\n","        # Afficher l'élément\n","        print(\"L'élément à l'index\", index, \"est :\", element)\n","\n","    except IndexError:\n","        # Gérer l'exception si l'index est invalide\n","        print(\"Erreur : L'index spécifié est invalide.\")\n","\n","# Créer une liste d'entiers (vous pouvez la modifier selon vos besoins)\n","my_list = [10, 20, 30, 40, 50]\n","\n","# Appeler la fonction pour accéder à un élément de la liste\n","access_list_element(my_list)\n","\n","\n","#3\n","def convert_to_number():\n","    try:\n","        # Demander à l'utilisateur d'entrer un nombre\n","        user_input = input(\"Entrez un nombre : \")\n","\n","        # Convertir l'entrée utilisateur en entier ou en flottant\n","        number = int(user_input) if user_input.isdigit() else float(user_input)\n","\n","        # Afficher le résultat\n","        print(\"Nombre converti :\", number)\n","\n","    except ValueError:\n","        # Gérer l'exception si l'entrée utilisateur ne peut pas être convertie en nombre\n","        print(\"Erreur : Veuillez entrer un nombre valide.\")\n","\n","# Appeler la fonction pour demander à l'utilisateur d'entrer un nombre\n","convert_to_number()\n","\n","\n","#4\n","class InvalidAgeException(Exception):\n","    pass\n","\n","def get_valid_age():\n","    try:\n","        # Demander à l'utilisateur d'entrer un âge\n","        age = int(input(\"Entrez votre âge : \"))\n","\n","        # Vérifier si l'âge est valide\n","        if age < 0 or age > 150:\n","            raise InvalidAgeException(\"L'âge doit être compris entre 0 et 150 ans.\")\n","\n","        # Si l'âge est valide, afficher un message de confirmation\n","        print(\"Âge valide :\", age)\n","\n","    except InvalidAgeException as e:\n","        # Gérer l'exception si l'âge est invalide et afficher un message d'erreur\n","        print(\"Erreur :\", e)\n","\n","# Appeler la fonction pour demander à l'utilisateur d'entrer un âge\n","get_valid_age()\n","\n","\n","\n","#5\n","class InvalidDivisorException(Exception):\n","    pass\n","\n","def divide_numbers(dividend, divisor):\n","    try:\n","        if divisor == 0:\n","            raise InvalidDivisorException(\"Division by zero is not allowed\")\n","        result = dividend / divisor\n","        return result\n","    except InvalidDivisorException as e:\n","        print(e)\n","\n","try:\n","    dividend = float(input(\"Enter the dividend: \"))\n","    divisor = float(input(\"Enter the divisor: \"))\n","    result = divide_numbers(dividend, divisor)\n","    print(\"Result:\", result)\n","except ValueError:\n","    print(\"Please enter valid numbers.\")\n","\n"],"metadata":{"id":"7cW3M0O_whma","colab":{"base_uri":"https://localhost:8080/"},"executionInfo":{"status":"ok","timestamp":1710158061160,"user_tz":-60,"elapsed":81001,"user":{"displayName":"Amandine Van de Winckel","userId":"01836789638994642216"}},"outputId":"76d6c2aa-eb1f-44a3-dcac-4565d4ed568d"},"execution_count":1,"outputs":[{"output_type":"stream","name":"stdout","text":["Entrez le numérateur : 52363\n","Entrez le dénominateur : 46568\n","Résultat de la division : 1.1244416766878542\n","Entrez l'index de l'élément à accéder : 445\n","Erreur : L'index spécifié est invalide.\n","Entrez un nombre : 7896\n","Nombre converti : 7896\n","Entrez votre âge : 65\n","Âge valide : 65\n","Enter the dividend: 97\n","Enter the divisor: 445\n","Result: 0.21797752808988763\n"]}]}],"metadata":{"kernelspec":{"display_name":"Python 3","language":"python","name":"python3"},"language_info":{"codemirror_mode":{"name":"ipython","version":3},"file_extension":".py","mimetype":"text/x-python","name":"python","nbconvert_exporter":"python","pygments_lexer":"ipython3","version":"3.7.5"},"vscode":{"interpreter":{"hash":"65c45682600b822032a055cbf04f0dc5abe5e3c026f7225f43ce560cd84c5728"}},"colab":{"provenance":[{"file_id":"1d3vFs22h4qfjlGlfk0KiWDnuKOHBRYQq","timestamp":1709729478439}]}},"nbformat":4,"nbformat_minor":0}